# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  buildntestnpush:
    docker:
      - image: circleci/python:buster
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: build pip package
          command: |
            ./build.sh

      - run:
          name: build container haprestio
          command: |
            cd docker
            docker build -t innofocus/haprestio:latest .
            cd -

      - run:
          name: build container testing
          command: |
            cd tests
            ./build.sh
            cd -

      - run:
          name: run tests
          command: |
            docker-compose up --exit-code-from testing --abort-on-container-exit

      - run:
          name: push container
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USER --password-stdin
            docker push innofocus/haprestio:latest

      - run:
          name: push package
          command: |
            pip3 install twine
            python3 setup.py sdist
            twine upload -u $PYPI_USER -p $PYPI_PASSWORD dist/*

workflows:
  version: 2
  bntnp:
    jobs:
      - buildntestnpush