# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:buster
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: build pip package
          command: |
            pip uninstall haprestio -y
            python3 setup.py bdist_wheel
            pip install dist/*
            [ -f docker/*whl ] && rm docker/*whl
            mv dist/* docker

      - run:
          name: build container
          command: |
            cd docker
            docker build -t innofocus/haprestio:latest .
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USER --password-stdin
            docker push innofocus/haprestio:latest
            cd -

      - run:
          name: artefacts dir
          command: |
            mkdir test-results

      - store_test_results:
         path: test-results
      - store_artifacts:
         path: test-results
         destination: tr1

  tests:
    docker:
      - image: circleci/python:buster

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: run compose
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USER --password-stdin
            docker-compose up -d

      - run:
          name: check app
          command: |
            mkdir test-results
            while docker-compose logs haprestio | tail -n 1 | grep "Waiting for consul"; do sleep 1; done
            sleep 1
            docker-compose exec -T haprestio /bin/sh -c "curl http://localhost:5080/api/v1/swagger.json" > test-results/output.txt

workflows:
  version: 2
  letsgo:
    jobs:
      - tests