# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:buster
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: build pip package
          command: |
            pip uninstall haprestio -y
            python3 setup.py bdist_wheel
            pip install dist/*
            [ -f docker/*whl ] && rm docker/*whl
            mv dist/* docker

      - run:
          name: build container
          command: |
            docker-compose build haprestio

      - store_test_results:
         path: test-results
      - store_artifacts:
         path: test-results
         destination: tr1

  tests:
    docker:
      - image: circleci/python:buster

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: run compose
          command: |
            docker-compose up -d

      - run:
          name: check app
          command: |
            curl http://localhost:5080/swagger.json > test-results/output.txt
